<a href="https://colab.research.google.com/github/harshitsonitech-eng/IDRA-Assignments/blob/main/E_Commers_sales_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files

uploaded = files.upload()

Saving Day8_Ecommerce_Sales_Dataset.csv to Day8_Ecommerce_Sales_Dataset.csv

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("Day8_Ecommerce_Sales_Dataset.csv")

print("Dataset loaded successfully!")
print("Rows and Columns:", df.shape)

display(df.head())

Dataset loaded successfully!
Rows and Columns: (100, 13)

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

In [3]:
print("First 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("\nRandom 5 Rows:")
display(df.sample(5))

print("\nShape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

First 5 Rows:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
0,1001,2026-02-27,Kabir Ali,Hyderabad,South,Electronics,Wireless Headphones,3,1499,0,4497.00,3.8,Cash on Delivery
1,1002,2026-01-24,Aditya Verma,Jammu,North,Sports,Running Shoes,1,2799,0,2799.00,4.1,Cash on Delivery
2,1003,2026-04-18,Sara Ahmed,Chennai,South,Electronics,Power Bank,2,1199,15,2038.30,4.6,Cash on Delivery
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card
4,1005,2026-03-30,Priya Menon,Jammu,North,Electronics,Smart Watch,1,3299,5,3134.05,4.2,UPI

Last 5 Rows:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
95,1096,2026-01-26,Aditya Verma,Kochi,South,Sports,Dumbbell Set,5,1999,5,9495.25,4.2,Credit Card
96,1097,2026-02-02,Arjun Nair,Mumbai,West,Clothing,T-Shirt,1,799,15,679.15,3.5,UPI
97,1098,2026-01-04,Yusuf Dar,Bengaluru,South,Home & Kitchen,Electric Kettle,4,1499,0,5996.00,4.2,Net Banking
98,1099,2026-03-06,Hiba Sheikh,Ahmedabad,West,Books,Machine Learning Basics,2,999,0,1998.00,3.8,UPI
99,1100,2026-02-08,Kabir Ali,Pune,West,Books,Data Science Handbook,5,899,0,4495.00,4.8,Debit Card

Random 5 Rows:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
87,1088,2026-06-06,Alina Shah,Lucknow,North,Books,Python Programming,4,749,15,2546.60,4.5,Debit Card
78,1079,2026-03-05,Aditya Verma,Mumbai,West,Clothing,Hoodie,1,1599,0,1599.00,3.5,Cash on Delivery
13,1014,2026-02-05,Dev Patel,Jaipur,North,Sports,Running Shoes,3,2799,0,8397.00,4.6,UPI
53,1054,2026-04-22,Aisha Mir,Chennai,South,Home & Kitchen,Coffee Maker,1,3499,15,2974.15,4.3,Net Banking
65,1066,2026-06-20,Dev Patel,Jaipur,North,Electronics,Smart Watch,2,3299,10,5938.20,4.7,Cash on Delivery

Shape: (100, 13)

Columns:
['Order_ID', 'Order_Date', 'Customer', 'City', 'Region', 'Category', 'Product', 'Quantity', 'Unit_Price', 'Discount_Percent', 'Total_Sales', 'Rating', 'Payment_Method']

Data Types:
Order_ID              int64
Order_Date           object
Customer             object
City                 object
Region               object
Category             object
Product              object
Quantity              int64
Unit_Price            int64
Discount_Percent      int64
Total_Sales         float64
Rating              float64
Payment_Method       object
dtype: object

In [4]:
print("Dataset Information:")
df.info()

print("\nDescriptive Statistics:")
display(df.describe())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          100 non-null    int64
 1   Order_Date        100 non-null    object
 2   Customer          100 non-null    object
 3   City              100 non-null    object
 4   Region            100 non-null    object
 5   Category          100 non-null    object
 6   Product           100 non-null    object
 7   Quantity          100 non-null    int64
 8   Unit_Price        100 non-null    int64
 9   Discount_Percent  100 non-null    int64
 10  Total_Sales       100 non-null    float64
 11  Rating            100 non-null    float64
 12  Payment_Method    100 non-null    object
dtypes: float64(2), int64(4), object(7)
memory usage: 10.3+ KB

Descriptive Statistics:

,Order_ID,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating
count,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,1050.500000,2.940000,1647.000000,6.500000,4472.629500,4.322000
std,29.011492,1.391315,970.054669,6.092718,3324.306691,0.414285
min,1001.000000,1.000000,499.000000,0.000000,449.100000,3.500000
25%,1025.750000,2.000000,799.000000,0.000000,1948.050000,4.100000
50%,1050.500000,3.000000,1499.000000,5.000000,3228.300000,4.300000
75%,1075.250000,4.000000,2499.000000,11.250000,6427.562500,4.700000
max,1100.000000,5.000000,3499.000000,15.000000,13995.000000,5.000000

In [5]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
Order_ID            0
Order_Date          0
Customer            0
City                0
Region              0
Category            0
Product             0
Quantity            0
Unit_Price          0
Discount_Percent    0
Total_Sales         0
Rating              0
Payment_Method      0
dtype: int64

In [12]:
total_sales = df["Total_Sales"].sum()
average_sales = df["Total_Sales"].mean()
highest_sale = df["Total_Sales"].max()
lowest_sale = df["Total_Sales"].min()
total_quantity = df["Quantity"].sum()
number_of_orders = df["Order_ID"].nunique()

print("Total Sales:", total_sales)
print("Average Sale:", average_sales)
print("Highest Sale:", highest_sale)
print("Lowest Sale:", lowest_sale)
print("Total Quantity Sold:", total_quantity)
print("Number of Orders:", number_of_orders)

Total Sales: 447262.95000000007
Average Sale: 4472.629500000001
Highest Sale: 13995.0
Lowest Sale: 449.1
Total Quantity Sold: 294
Number of Orders: 100

In [13]:
category_sales = (
    df.groupby("Category")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Category-wise Sales:")
display(category_sales)

Category-wise Sales:

Category
Sports            136026.45
Home & Kitchen    113329.90
Electronics        92086.00
Clothing           69028.20
Books              36792.40
Name: Total_Sales, dtype: float64

In [14]:
city_sales = (
    df.groupby("City")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("City-wise Sales:")
display(city_sales)

City-wise Sales:

City
Hyderabad      59076.45
Chennai        47493.20
Lucknow        46194.65
Pune           41908.55
Mumbai         41457.80
Kochi          37257.50
Chandigarh     34539.65
Delhi          30882.80
Jaipur         25534.00
Kolkata        20169.00
Jammu          16059.75
Ahmedabad      14788.70
Bengaluru      13524.30
Srinagar       11778.60
Bhubaneswar     6598.00
Name: Total_Sales, dtype: float64

In [16]:
product_sales = (
    df.groupby("Product")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Product-wise Sales:")
display(product_sales)

Product-wise Sales:

Product
Coffee Maker               51610.25
Jacket                     47106.15
Cricket Bat                41483.40
Running Shoes              41285.25
Wireless Headphones        33877.40
Dumbbell Set               30184.90
Mechanical Keyboard        26489.40
Electric Kettle            26382.40
Mixer Grinder              25341.55
Smart Watch                15670.25
Yoga Mat                   12765.80
Atomic Habits              11590.65
Football                   10307.10
Water Bottle                9995.70
Wireless Mouse              9574.35
T-Shirt                     7790.25
Hoodie                      7675.20
Python Programming          7527.45
The Alchemist               7485.00
Power Bank                  6474.60
Jeans                       6456.60
Machine Learning Basics     5694.30
Data Science Handbook       4495.00
Name: Total_Sales, dtype: float64

In [18]:
payment_sales = (
    df.groupby("Payment_Method")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Payment Method-wise Sales:")
display(payment_sales)

Payment Method-wise Sales:

Payment_Method
Credit Card         106540.25
Debit Card           98064.90
Net Banking          96371.25
UPI                  96163.25
Cash on Delivery     50123.30
Name: Total_Sales, dtype: float64

In [19]:
region_sales = (
    df.groupby("Region")["Total_Sales"]
    .sum()
    .sort_values(ascending=False)
)

print("Region-wise Sales:")
display(region_sales)

Region-wise Sales:

Region
North    164989.45
South    157351.45
West      98155.05
East      26767.00
Name: Total_Sales, dtype: float64

In [20]:
print("Top 5 Products by Sales:")
display(product_sales.head(5))

Top 5 Products by Sales:

Product
Coffee Maker           51610.25
Jacket                 47106.15
Cricket Bat            41483.40
Running Shoes          41285.25
Wireless Headphones    33877.40
Name: Total_Sales, dtype: float64

In [21]:
print("Bottom 5 Products by Sales:")
display(product_sales.tail(5))

Bottom 5 Products by Sales:

Product
The Alchemist              7485.0
Power Bank                 6474.6
Jeans                      6456.6
Machine Learning Basics    5694.3
Data Science Handbook      4495.0
Name: Total_Sales, dtype: float64

In [22]:
print("Top 10 Orders by Sales:")

top_orders = df.sort_values(
    "Total_Sales",
    ascending=False
).head(10)

display(top_orders)

Top 10 Orders by Sales:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
69,1070,2026-06-30,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,3.8,Net Banking
79,1080,2026-05-25,Aditya Verma,Delhi,North,Clothing,Jacket,4,2499,0,9996.00,4.6,Debit Card
51,1052,2026-03-13,Rohan Mehta,Chandigarh,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.2,Debit Card
3,1004,2026-03-13,Kabir Ali,Lucknow,North,Electronics,Mechanical Keyboard,4,2499,5,9496.20,4.1,Debit Card

In [23]:
print("Orders with Total Sales Greater Than 10000:")

high_sales_orders = df[df["Total_Sales"] > 10000]

display(high_sales_orders)

Orders with Total Sales Greater Than 10000:

,Order_ID,Order_Date,Customer,City,Region,Category,Product,Quantity,Unit_Price,Discount_Percent,Total_Sales,Rating,Payment_Method
12,1013,2026-03-09,Maryam Khan,Lucknow,North,Clothing,Jacket,5,2499,15,10620.75,4.8,Net Banking
47,1048,2026-06-24,Sara Ahmed,Lucknow,North,Home & Kitchen,Coffee Maker,3,3499,0,10497.00,5.0,UPI
48,1049,2026-03-02,Ishita Gupta,Mumbai,West,Sports,Running Shoes,5,2799,0,13995.00,4.0,Net Banking
52,1053,2026-01-08,Ananya Singh,Hyderabad,South,Sports,Running Shoes,5,2799,5,13295.25,4.2,Credit Card
84,1085,2026-01-28,Sana Malik,Hyderabad,South,Home & Kitchen,Coffee Maker,4,3499,10,12596.40,4.3,Net Banking
89,1090,2026-05-13,Aditya Verma,Lucknow,North,Sports,Cricket Bat,5,2499,0,12495.00,3.8,Credit Card

In [24]:
top_category = category_sales.idxmax()
top_city = city_sales.idxmax()
top_product = product_sales.idxmax()
top_region = region_sales.idxmax()
top_payment = payment_sales.idxmax()

print("===== FINAL OBSERVATIONS =====")

print("1. Highest-selling category:", top_category)
print("2. Highest-selling city:", top_city)
print("3. Highest-selling product:", top_product)
print("4. Highest-selling region:", top_region)
print("5. Highest-sales payment method:", top_payment)
print("6. Total sales:", total_sales)
print("7. Total quantity sold:", total_quantity)
print("8. Total number of orders:", number_of_orders)

===== FINAL OBSERVATIONS =====
1. Highest-selling category: Sports
2. Highest-selling city: Hyderabad
3. Highest-selling product: Coffee Maker
4. Highest-selling region: North
5. Highest-sales payment method: Credit Card
6. Total sales: 447262.95000000007
7. Total quantity sold: 294
8. Total number of orders: 100